//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostOfGoodsSold
    {
        public int ID { get; set; }
        public string CogsCompanyName { get; set; }
        public string CogsSiteName { get; set; }
        public int CogsStatus { get; set; }
        public string CogsGPCode { get; set; }
        public Nullable<System.DateTime> CogsDueDate { get; set; }
        public string CogsGPCategory { get; set; }
        public string CogsDescription { get; set; }
        public long CogsSalesOrderId { get; set; }
        public decimal CogsItemQuantity { get; set; }
        public decimal CogsItemListPrice { get; set; }
        public decimal CogsItemBuyPrice { get; set; }
        public Nullable<long> CogsLedgerId { get; set; }
    }
}
