//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Temp_InvoiceLedger
    {
        public string Type { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime Date { get; set; }
        public string CustRef { get; set; }
        public string CustName { get; set; }
        public string OrderNo { get; set; }
        public string Address { get; set; }
        public decimal Gross { get; set; }
        public string UserDefined { get; set; }
        public string SaleDocument { get; set; }
        public decimal Net { get; set; }
        public decimal VAT { get; set; }
        public Nullable<decimal> OTTA { get; set; }
        public long Id { get; set; }
    }
}
