//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class GP_Temp_OutstandingInvoices
    {
        public string CustRef { get; set; }
        public string CustName { get; set; }
        public string ClassID { get; set; }
        public string TerritoryID { get; set; }
        public string DocumentNumber { get; set; }
        public string Type { get; set; }
        public string Date { get; set; }
        public string DueDate { get; set; }
        public Nullable<decimal> OriginalTrxAmount { get; set; }
        public Nullable<decimal> CurrentTrxAmount { get; set; }
        public Nullable<decimal> Days0 { get; set; }
        public Nullable<decimal> Days1 { get; set; }
        public Nullable<decimal> Days2 { get; set; }
        public Nullable<decimal> Days3 { get; set; }
        public Nullable<decimal> Days4 { get; set; }
        public Nullable<decimal> Days5 { get; set; }
        public Nullable<decimal> Days6 { get; set; }
        public long Id { get; set; }
    }
}
