//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.DateTime LogDate { get; set; }
        public string ExcelPath { get; set; }
        public string ImportType { get; set; }
        public Nullable<long> NumberOfRowsImported { get; set; }
        public long Id { get; set; }
    }
}
