//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceGLBridge
    {
        public Nullable<short> MaintenanceType { get; set; }
        public Nullable<int> GLNumber { get; set; }
        public long Id { get; set; }
    }
}
