//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingInvoicesExtended
    {
        public string CustRef { get; set; }
        public string CustName { get; set; }
        public string ClassID { get; set; }
        public string DocumentNumber { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal OriginalTrxAmount { get; set; }
        public decimal CurrentTrxAmount { get; set; }
        public decimal Current { get; set; }
        public Nullable<decimal> Days31_60 { get; set; }
        public Nullable<decimal> Days61_90 { get; set; }
        public Nullable<decimal> Days91_180 { get; set; }
        public Nullable<decimal> Days181_270 { get; set; }
        public Nullable<decimal> Days271_364 { get; set; }
        public Nullable<decimal> Days365_Plus { get; set; }
    }
}
