//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostedInvoicesExtended
    {
        public long ID { get; set; }
        public long JournalEntry { get; set; }
        public string Series { get; set; }
        public System.DateTime TrxDate { get; set; }
        public System.DateTime OriginatingTrxDate { get; set; }
        public Nullable<short> JonasGroup { get; set; }
        public string GroupName { get; set; }
        public string LongReference { get; set; }
        public string MaintTypeDescription { get; set; }
        public string ReportingDescription { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string Reference { get; set; }
        public string OriginatingMasterID { get; set; }
        public string OriginatingMasterName { get; set; }
        public string OriginatingDocumentNo { get; set; }
        public bool Voided { get; set; }
        public string OriginatingTrxSource { get; set; }
        public string OriginatingTrxType { get; set; }
        public string OriginatingType { get; set; }
        public string UserWhoPosted { get; set; }
    }
}
