//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sage_Temp_InvoiceLedger
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string CustRef { get; set; }
        public Nullable<int> GL { get; set; }
        public string UniqueID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string Type { get; set; }
        public string Currency { get; set; }
        public string DeliveryAddress { get; set; }
        public string CustOrderNo { get; set; }
        public string InvoiceNo { get; set; }
        public string CustName { get; set; }
        public long Id { get; set; }
    }
}
