//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleLedgerExtended
    {
        public string UniqueID { get; set; }
        public string CustRef { get; set; }
        public string CustName { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> GL { get; set; }
        public string GLDescription { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public string InvoiceNo { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<short> JonasGroup { get; set; }
        public string JonasGroupName { get; set; }
        public Nullable<short> MaintenanceType { get; set; }
        public string MaintTypeDescription { get; set; }
        public string ReportingDescription { get; set; }
        public string EntryType { get; set; }
        public decimal QtyValue { get; set; }
        public decimal NetValue { get; set; }
        public decimal TaxValue { get; set; }
        public decimal GrossValue { get; set; }
        public decimal ProfitValue { get; set; }
        public string CustOrderNo { get; set; }
        public string ImportType { get; set; }
        public string Category { get; set; }
        public Nullable<double> UniqueID2 { get; set; }
        public Nullable<short> MiniPack { get; set; }
        public string SiteSurveyDate { get; set; }
        public string BacklogComments { get; set; }
        public string Deposit { get; set; }
        public string AssignedTo { get; set; }
        public string MegJobNo { get; set; }
        public Nullable<short> DirectDebit { get; set; }
        public string Spare1 { get; set; }
        public string TerminalTypeName { get; set; }
        public string Spare2 { get; set; }
        public string AdminStatusName { get; set; }
        public Nullable<long> LedgerId { get; set; }
    }
}
