//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL_JonasSageImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBacklogHistory
    {
        public int SbhID { get; set; }
        public System.DateTime SbhDate { get; set; }
        public decimal SbhBacklogGrossTotal { get; set; }
        public decimal SbhBacklogNetTotal { get; set; }
        public decimal SbhInstalledGrossTotal { get; set; }
        public decimal SbhMonthlyBacklogNotInstalledGross { get; set; }
        public decimal SbhMonthlyBacklogNotInstalledNet { get; set; }
        public decimal SbhMonthlyRunningInstalledTotalGross { get; set; }
        public decimal SbhMonthlyRunningInstalledTotalNet { get; set; }
    }
}
